# Generated by Django 5.0.3 on 2024-03-08 10:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('lastname', models.CharField(max_length=100)),
                ('biography', models.TextField()),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 44, 6, 919559, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 44, 6, 919819, tzinfo=datetime.timezone.utc))),
                ('is_published', models.BooleanField()),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework2.author')),
            ],
        ),
    ]
