# Generated by Django 5.0.3 on 2024-03-15 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework2', '0002_author_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product2',
            name='photo',
            field=models.ImageField(default='default_product.jpg', upload_to='product_photos/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 51, 52, 843130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 12, 51, 52, 843130, tzinfo=datetime.timezone.utc)),
        ),
    ]
